### ISSUE TITLE
New conversations do not work until a page reload

### ISSUE THREAD

**Issue by everson-tavares-movile** [Movile/Rocket.Chat#2]
Quando você vai falar com alguém no privado pela primeira vez, as mensagem ficam cinza como se não tivessem sido enviadas, após dar refresh aparece normal. A pessoa está recebendo normalmente.

**Comment by alexandre-zia-movile** [comment]
when you star a new conversation with someone you've have spoken before, the send messages appears greyed out, and the answers are not shown.
After a page restart (Command+R/Control+R) the conversation works as expected

**Comment by fabio-santos-movile** [comment]
another details...

1. The other side will see your message
2. if answer was sent, on the user list you will see a notification and number of unread messages, but you will not be able read until the reload.

**Comment by engelgabriel** [comment]
Ref: https://github.com/RocketChat/Rocket.Chat/issues/4322
